name: Merge Approval Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested, ready_for_review]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the secret GitHub token as an environment variable

    steps:
      - name: Checkout the PR code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/gh-actions@v2
        with:
          gh-token: ${{ secrets.GH_TOKEN }}  # Pass the token to the GitHub CLI action

      - name: Get the PR reviews
        id: pr_reviews
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REVIEWS=$(gh pr view $PR_NUMBER --json reviews --jq '.reviews')
          echo "Reviews: $REVIEWS"
          echo "::set-output name=reviews::$REVIEWS"

      - name: Ensure PR-Merge and Test-DevOps Approvals
        id: check_approval
        run:
